<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>f47ee2ef-c432-47c6-8b9a-7c27baa6e123</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Controllers\NotificationSettingsController.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="12.0.0" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="EPPlus" Version="7.7.3" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.22" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.22" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.15.0" />

		<PackageReference Include="NLog.Web.AspNetCore" Version="6.1.0" />

		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Data\Data.csproj" />
		<ProjectReference Include="..\DTO\DTO.csproj" />
		<ProjectReference Include="..\Entities\Entities.csproj" />
		<ProjectReference Include="..\Mapping\Mapping.csproj" />
		<ProjectReference Include="..\Repositories\Repositories.csproj" />
	</ItemGroup>

</Project>